name: permeability-tutorial
channels:
 - conda-forge
 - omnia
dependencies:
 - mdtraj==1.9.5
 - pip==21.1.2
 - openmmforcefields
 - openff-forcefields>=2.0.0
 - numpy>=1.16.0
 - python=3.8
 - scipy>=0.19.1
 - cudatoolkit==10.0.130
 - Cython>=0.29.16
 - openmm==7.5
